// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tukpjeekbmpiliwuhrgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1a3BqZWVrYm1waWxpd3Vocmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTg3MjIsImV4cCI6MjA2MTY5NDcyMn0.z1i9cn9tynaO-IFOOYZ6wmPAtla2N54MVAaF8-QQIEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);